version: '3.9'
services:
  api-node:
    build: ./services/api-node
    ports:
      - "3000:3000"
    env_file:
      - services/api-node/.env.sample
  worker-python:
    build: ./services/worker-python
    ports:
      - "8000:8000"
    env_file:
      - services/worker-python/.env.sample